kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: influxdb-scc
subjects:
  - kind: ServiceAccount
    name: influxdb
    namespace: namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-use-anyuid-scc
