apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: battery-demo
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: ''
    server: https://kubernetes.default.svc
  source:
    path: groups/dev
    repoURL: https://github.com/ortwinschneider/battery-simulation
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
