apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./namespace.yaml
- ../../components

patches:
 - target:
      group: operators.coreos.com
      version: v1
      kind: OperatorGroup
      name: og-battery-simulation
   path: og-patch.yaml

namespace: battery-demo
