apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: mqtt-broker
  labels:
    app.kubernetes.io/part-of: IoT-Hub
spec:
  acceptors:
    - connectionsAllowed: -1
      expose: true
      name: all
      port: 61616
  adminPassword: admin
  adminUser: admin
  console:
    expose: true
  deploymentPlan:
    image: placeholder
    jolokiaAgentEnabled: false
    journalType: nio
    managementRBACEnabled: true
    messageMigration: false
    persistenceEnabled: false
    requireLogin: false
    size: 1